update=06/09/18 09:33:20
version=1
last_client=kicad
[general]
version=1
RootSch=
BoardNm=
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=E:/Program Files/KiCad/share/kicad/library/4xxx
LibName2=E:/Program Files/KiCad/share/kicad/library/4xxx_IEEE
LibName3=E:/Program Files/KiCad/share/kicad/library/74xgxx
LibName4=E:/Program Files/KiCad/share/kicad/library/74xx
LibName5=E:/Program Files/KiCad/share/kicad/library/74xx_IEEE
LibName6=E:/Program Files/KiCad/share/kicad/library/ac-dc
LibName7=E:/Program Files/KiCad/share/kicad/library/actel
LibName8=E:/Program Files/KiCad/share/kicad/library/adc-dac
LibName9=E:/Program Files/KiCad/share/kicad/library/allegro
LibName10=E:/Program Files/KiCad/share/kicad/library/Altera
LibName11=E:/Program Files/KiCad/share/kicad/library/Amplifier_Audio
LibName12=E:/Program Files/KiCad/share/kicad/library/Amplifier_Buffer
LibName13=E:/Program Files/KiCad/share/kicad/library/Amplifier_Current
LibName14=E:/Program Files/KiCad/share/kicad/library/Amplifier_Difference
LibName15=E:/Program Files/KiCad/share/kicad/library/Amplifier_Instrumentation
LibName16=E:/Program Files/KiCad/share/kicad/library/Amplifier_Operational
LibName17=E:/Program Files/KiCad/share/kicad/library/Amplifier_Video
LibName18=E:/Program Files/KiCad/share/kicad/library/Analog
LibName19=E:/Program Files/KiCad/share/kicad/library/Analog_ADC
LibName20=E:/Program Files/KiCad/share/kicad/library/Analog_DAC
LibName21=E:/Program Files/KiCad/share/kicad/library/analog_devices
LibName22=E:/Program Files/KiCad/share/kicad/library/Analog_Switch
LibName23=E:/Program Files/KiCad/share/kicad/library/analog_switches
LibName24=E:/Program Files/KiCad/share/kicad/library/atmel
LibName25=E:/Program Files/KiCad/share/kicad/library/audio
LibName26=E:/Program Files/KiCad/share/kicad/library/banez_custom
LibName27=E:/Program Files/KiCad/share/kicad/library/battery_management
LibName28=E:/Program Files/KiCad/share/kicad/library/bbd
LibName29=E:/Program Files/KiCad/share/kicad/library/bosch
LibName30=E:/Program Files/KiCad/share/kicad/library/brooktre
LibName31=E:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName32=E:/Program Files/KiCad/share/kicad/library/cmos4000
LibName33=E:/Program Files/KiCad/share/kicad/library/Comparator
LibName34=E:/Program Files/KiCad/share/kicad/library/conn
LibName35=E:/Program Files/KiCad/share/kicad/library/Connector
LibName36=E:/Program Files/KiCad/share/kicad/library/Connector_Generic
LibName37=E:/Program Files/KiCad/share/kicad/library/Connector_Generic_MountingPin
LibName38=E:/Program Files/KiCad/share/kicad/library/Connector_Generic_Shielded
LibName39=E:/Program Files/KiCad/share/kicad/library/contrib
LibName40=E:/Program Files/KiCad/share/kicad/library/Converter_ACDC
LibName41=E:/Program Files/KiCad/share/kicad/library/Converter_DCDC
LibName42=E:/Program Files/KiCad/share/kicad/library/CPLD_Altera
LibName43=E:/Program Files/KiCad/share/kicad/library/CPLD_Xilinx
LibName44=E:/Program Files/KiCad/share/kicad/library/CPU
LibName45=E:/Program Files/KiCad/share/kicad/library/CPU_NXP_6800
LibName46=E:/Program Files/KiCad/share/kicad/library/CPU_NXP_68000
LibName47=E:/Program Files/KiCad/share/kicad/library/CPU_PowerPC
LibName48=E:/Program Files/KiCad/share/kicad/library/Custom_Logic_74xxx
LibName49=E:/Program Files/KiCad/share/kicad/library/cypress
LibName50=E:/Program Files/KiCad/share/kicad/library/dc-dc
LibName51=E:/Program Files/KiCad/share/kicad/library/Decawave
LibName52=E:/Program Files/KiCad/share/kicad/library/device
LibName53=E:/Program Files/KiCad/share/kicad/library/digital-audio
LibName54=E:/Program Files/KiCad/share/kicad/library/diode
LibName55=E:/Program Files/KiCad/share/kicad/library/Diode_Bridge
LibName56=E:/Program Files/KiCad/share/kicad/library/Diode_Laser
LibName57=E:/Program Files/KiCad/share/kicad/library/display
LibName58=E:/Program Files/KiCad/share/kicad/library/Display_Character
LibName59=E:/Program Files/KiCad/share/kicad/library/Display_Graphic
LibName60=E:/Program Files/KiCad/share/kicad/library/Driver_Display
LibName61=E:/Program Files/KiCad/share/kicad/library/Driver_FET
LibName62=E:/Program Files/KiCad/share/kicad/library/driver_gate
LibName63=E:/Program Files/KiCad/share/kicad/library/Driver_LED
LibName64=E:/Program Files/KiCad/share/kicad/library/Driver_Motor
LibName65=E:/Program Files/KiCad/share/kicad/library/Driver_Relay
LibName66=E:/Program Files/KiCad/share/kicad/library/dsp
LibName67=E:/Program Files/KiCad/share/kicad/library/DSP_Freescale
LibName68=E:/Program Files/KiCad/share/kicad/library/DSP_Microchip_DSPIC33
LibName69=E:/Program Files/KiCad/share/kicad/library/DSP_Motorola
LibName70=E:/Program Files/KiCad/share/kicad/library/DSP_Texas
LibName71=E:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName72=E:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName73=E:/Program Files/KiCad/share/kicad/library/Espressif
LibName74=E:/Program Files/KiCad/share/kicad/library/Filter
LibName75=E:/Program Files/KiCad/share/kicad/library/FPGA_Actel
LibName76=E:/Program Files/KiCad/share/kicad/library/FPGA_Microsemi
LibName77=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx
LibName78=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Artix7
LibName79=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Kintex7
LibName80=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Spartan6
LibName81=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex5
LibName82=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex6
LibName83=E:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex7
LibName84=E:/Program Files/KiCad/share/kicad/library/ftdi
LibName85=E:/Program Files/KiCad/share/kicad/library/gennum
LibName86=E:/Program Files/KiCad/share/kicad/library/GPU
LibName87=E:/Program Files/KiCad/share/kicad/library/Graphic
LibName88=E:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName89=E:/Program Files/KiCad/share/kicad/library/hc11
LibName90=E:/Program Files/KiCad/share/kicad/library/infineon
LibName91=E:/Program Files/KiCad/share/kicad/library/intel
LibName92=E:/Program Files/KiCad/share/kicad/library/interface
LibName93=E:/Program Files/KiCad/share/kicad/library/Interface_CAN_LIN
LibName94=E:/Program Files/KiCad/share/kicad/library/Interface_CurrentLoop
LibName95=E:/Program Files/KiCad/share/kicad/library/Interface_Ethernet
LibName96=E:/Program Files/KiCad/share/kicad/library/Interface_Expansion
LibName97=E:/Program Files/KiCad/share/kicad/library/Interface_HID
LibName98=E:/Program Files/KiCad/share/kicad/library/Interface_LineDriver
LibName99=E:/Program Files/KiCad/share/kicad/library/Interface_Optical
LibName100=E:/Program Files/KiCad/share/kicad/library/Interface_Telecom
LibName101=E:/Program Files/KiCad/share/kicad/library/Interface_UART
LibName102=E:/Program Files/KiCad/share/kicad/library/Interface_USB
LibName103=E:/Program Files/KiCad/share/kicad/library/intersil
LibName104=E:/Program Files/KiCad/share/kicad/library/ir
LibName105=E:/Program Files/KiCad/share/kicad/library/Isolator
LibName106=E:/Program Files/KiCad/share/kicad/library/Isolator_Analog
LibName107=E:/Program Files/KiCad/share/kicad/library/Jumper
LibName108=E:/Program Files/KiCad/share/kicad/library/Lattice
LibName109=E:/Program Files/KiCad/share/kicad/library/LED
LibName110=E:/Program Files/KiCad/share/kicad/library/leds
LibName111=E:/Program Files/KiCad/share/kicad/library/LEM
LibName112=E:/Program Files/KiCad/share/kicad/library/linear
LibName113=E:/Program Files/KiCad/share/kicad/library/Logic_74xgxx
LibName114=E:/Program Files/KiCad/share/kicad/library/Logic_74xx
LibName115=E:/Program Files/KiCad/share/kicad/library/Logic_CMOS_4000
LibName116=E:/Program Files/KiCad/share/kicad/library/Logic_CMOS_IEEE
LibName117=E:/Program Files/KiCad/share/kicad/library/Logic_LevelTranslator
LibName118=E:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName119=E:/Program Files/KiCad/share/kicad/library/Logic_TTL_IEEE
LibName120=E:/Program Files/KiCad/share/kicad/library/maxim
LibName121=E:/Program Files/KiCad/share/kicad/library/MCU_AnalogDevices
LibName122=E:/Program Files/KiCad/share/kicad/library/MCU_Cypress
LibName123=E:/Program Files/KiCad/share/kicad/library/MCU_Espressif
LibName124=E:/Program Files/KiCad/share/kicad/library/MCU_Intel
LibName125=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_8051
LibName126=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_ATmega
LibName127=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_ATtiny
LibName128=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_AVR
LibName129=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC10
LibName130=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC12
LibName131=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC16
LibName132=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC18
LibName133=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC24
LibName134=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC32
LibName135=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_SAME
LibName136=E:/Program Files/KiCad/share/kicad/library/MCU_Microchip_SAML
LibName137=E:/Program Files/KiCad/share/kicad/library/MCU_Module
LibName138=E:/Program Files/KiCad/share/kicad/library/MCU_Nordic
LibName139=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_ColdFire
LibName140=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_HC11
LibName141=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_HC12
LibName142=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_HCS12
LibName143=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_Kinetis
LibName144=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_LPC
LibName145=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_MAC7100
LibName146=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_MCore
LibName147=E:/Program Files/KiCad/share/kicad/library/MCU_NXP_S08
LibName148=E:/Program Files/KiCad/share/kicad/library/MCU_Parallax
LibName149=E:/Program Files/KiCad/share/kicad/library/MCU_SiFive
LibName150=E:/Program Files/KiCad/share/kicad/library/MCU_SiliconLabs
LibName151=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM8
LibName152=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32
LibName153=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F0
LibName154=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F1
LibName155=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F2
LibName156=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F3
LibName157=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F4
LibName158=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F7
LibName159=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32H7
LibName160=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L0
LibName161=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L1
LibName162=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L4
LibName163=E:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L4+
LibName164=E:/Program Files/KiCad/share/kicad/library/MCU_Texas
LibName165=E:/Program Files/KiCad/share/kicad/library/MCU_Texas_MSP430
LibName166=E:/Program Files/KiCad/share/kicad/library/mechanical
LibName167=E:/Program Files/KiCad/share/kicad/library/memory
LibName168=E:/Program Files/KiCad/share/kicad/library/Memory_Controller
LibName169=E:/Program Files/KiCad/share/kicad/library/Memory_EEPROM
LibName170=E:/Program Files/KiCad/share/kicad/library/Memory_EPROM
LibName171=E:/Program Files/KiCad/share/kicad/library/Memory_Flash
LibName172=E:/Program Files/KiCad/share/kicad/library/Memory_NVRAM
LibName173=E:/Program Files/KiCad/share/kicad/library/Memory_RAM
LibName174=E:/Program Files/KiCad/share/kicad/library/Memory_ROM
LibName175=E:/Program Files/KiCad/share/kicad/library/Memory_UniqueID
LibName176=E:/Program Files/KiCad/share/kicad/library/microchip
LibName177=E:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName178=E:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName179=E:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName180=E:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName181=E:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName182=E:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName183=E:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName184=E:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName185=E:/Program Files/KiCad/share/kicad/library/modules
LibName186=E:/Program Files/KiCad/share/kicad/library/Motor
LibName187=E:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName188=E:/Program Files/KiCad/share/kicad/library/motorola
LibName189=E:/Program Files/KiCad/share/kicad/library/motors
LibName190=E:/Program Files/KiCad/share/kicad/library/msp430
LibName191=E:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName192=E:/Program Files/KiCad/share/kicad/library/nxp
LibName193=E:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName194=E:/Program Files/KiCad/share/kicad/library/onsemi
LibName195=E:/Program Files/KiCad/share/kicad/library/opto
LibName196=E:/Program Files/KiCad/share/kicad/library/Oscillator
LibName197=E:/Program Files/KiCad/share/kicad/library/Oscillators
LibName198=E:/Program Files/KiCad/share/kicad/library/philips
LibName199=E:/Program Files/KiCad/share/kicad/library/Potentiometer_Digital
LibName200=E:/Program Files/KiCad/share/kicad/library/power
LibName201=E:/Program Files/KiCad/share/kicad/library/Power_Management
LibName202=E:/Program Files/KiCad/share/kicad/library/Power_Protection
LibName203=E:/Program Files/KiCad/share/kicad/library/Power_Supervisor
LibName204=E:/Program Files/KiCad/share/kicad/library/powerint
LibName205=E:/Program Files/KiCad/share/kicad/library/pspice
LibName206=E:/Program Files/KiCad/share/kicad/library/Reference_Current
LibName207=E:/Program Files/KiCad/share/kicad/library/Reference_Voltage
LibName208=E:/Program Files/KiCad/share/kicad/library/references
LibName209=E:/Program Files/KiCad/share/kicad/library/regul
LibName210=E:/Program Files/KiCad/share/kicad/library/Regulator_Controller
LibName211=E:/Program Files/KiCad/share/kicad/library/Regulator_Current
LibName212=E:/Program Files/KiCad/share/kicad/library/Regulator_Linear
LibName213=E:/Program Files/KiCad/share/kicad/library/Regulator_SwitchedCapacitor
LibName214=E:/Program Files/KiCad/share/kicad/library/Regulator_Switching
LibName215=E:/Program Files/KiCad/share/kicad/library/Relay
LibName216=E:/Program Files/KiCad/share/kicad/library/Relay_SolidState
LibName217=E:/Program Files/KiCad/share/kicad/library/relays
LibName218=E:/Program Files/KiCad/share/kicad/library/RF
LibName219=E:/Program Files/KiCad/share/kicad/library/RF_AM_FM
LibName220=E:/Program Files/KiCad/share/kicad/library/RF_Amplifier
LibName221=E:/Program Files/KiCad/share/kicad/library/RF_Bluetooth
LibName222=E:/Program Files/KiCad/share/kicad/library/RF_GPS
LibName223=E:/Program Files/KiCad/share/kicad/library/RF_Mixer
LibName224=E:/Program Files/KiCad/share/kicad/library/RF_Module
LibName225=E:/Program Files/KiCad/share/kicad/library/RF_RFID
LibName226=E:/Program Files/KiCad/share/kicad/library/RF_Switch
LibName227=E:/Program Files/KiCad/share/kicad/library/RF_WiFi
LibName228=E:/Program Files/KiCad/share/kicad/library/RF_ZigBee
LibName229=E:/Program Files/KiCad/share/kicad/library/rfcom
LibName230=E:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName231=E:/Program Files/KiCad/share/kicad/library/Sensor
LibName232=E:/Program Files/KiCad/share/kicad/library/Sensor_Audio
LibName233=E:/Program Files/KiCad/share/kicad/library/Sensor_Current
LibName234=E:/Program Files/KiCad/share/kicad/library/Sensor_Gas
LibName235=E:/Program Files/KiCad/share/kicad/library/Sensor_Humidity
LibName236=E:/Program Files/KiCad/share/kicad/library/Sensor_Magnetic
LibName237=E:/Program Files/KiCad/share/kicad/library/Sensor_Motion
LibName238=E:/Program Files/KiCad/share/kicad/library/Sensor_Optical
LibName239=E:/Program Files/KiCad/share/kicad/library/Sensor_Pressure
LibName240=E:/Program Files/KiCad/share/kicad/library/Sensor_Proximity
LibName241=E:/Program Files/KiCad/share/kicad/library/Sensor_Temperature
LibName242=E:/Program Files/KiCad/share/kicad/library/Sensor_Touch
LibName243=E:/Program Files/KiCad/share/kicad/library/Sensor_Voltage
LibName244=E:/Program Files/KiCad/share/kicad/library/sensors
LibName245=E:/Program Files/KiCad/share/kicad/library/silabs
LibName246=E:/Program Files/KiCad/share/kicad/library/siliconi
LibName247=E:/Program Files/KiCad/share/kicad/library/stm8
LibName248=E:/Program Files/KiCad/share/kicad/library/stm32
LibName249=E:/Program Files/KiCad/share/kicad/library/supertex
LibName250=E:/Program Files/KiCad/share/kicad/library/Switch
LibName251=E:/Program Files/KiCad/share/kicad/library/switches
LibName252=E:/Program Files/KiCad/share/kicad/library/texas
LibName253=E:/Program Files/KiCad/share/kicad/library/Timer
LibName254=E:/Program Files/KiCad/share/kicad/library/Timer_PLL
LibName255=E:/Program Files/KiCad/share/kicad/library/Timer_RTC
LibName256=E:/Program Files/KiCad/share/kicad/library/transf
LibName257=E:/Program Files/KiCad/share/kicad/library/Transformer
LibName258=E:/Program Files/KiCad/share/kicad/library/Transistor
LibName259=E:/Program Files/KiCad/share/kicad/library/Transistor_Array
LibName260=E:/Program Files/KiCad/share/kicad/library/Transistor_BJT
LibName261=E:/Program Files/KiCad/share/kicad/library/Transistor_FET
LibName262=E:/Program Files/KiCad/share/kicad/library/Transistor_IGBT
LibName263=E:/Program Files/KiCad/share/kicad/library/transistors
LibName264=E:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName265=E:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName266=E:/Program Files/KiCad/share/kicad/library/Valve
LibName267=E:/Program Files/KiCad/share/kicad/library/valves
LibName268=E:/Program Files/KiCad/share/kicad/library/video
LibName269=E:/Program Files/KiCad/share/kicad/library/wiznet
LibName270=E:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName271=E:/Program Files/KiCad/share/kicad/library/Xicor
LibName272=E:/Program Files/KiCad/share/kicad/library/xilinx
LibName273=E:/Program Files/KiCad/share/kicad/library/xilinx-artix7
LibName274=E:/Program Files/KiCad/share/kicad/library/xilinx-kintex7
LibName275=E:/Program Files/KiCad/share/kicad/library/xilinx-spartan6
LibName276=E:/Program Files/KiCad/share/kicad/library/xilinx-virtex5
LibName277=E:/Program Files/KiCad/share/kicad/library/xilinx-virtex6
LibName278=E:/Program Files/KiCad/share/kicad/library/xilinx-virtex7
LibName279=E:/Program Files/KiCad/share/kicad/library/zetex
LibName280=E:/Program Files/KiCad/share/kicad/library/Zilog
